version: "3.9"

services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ${CONFIGS}/qbittorrent/:/config
      - ${DOWNLOADS}:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080

  # Feeds with torrents to radarr and sonarr
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
      # - RUN_OPTS=run options here #optional
    volumes:
      - ${CONFIGS}/jackett/:/config
      - ${DOWNLOADS}/blackhole:/downloads
    ports:
      - 9117:9117


  # for automaticly having movies
  radarr:
    image: linuxserver/radarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGS}/radarr:/config
      - ${DOWNLOADS}/completed/movies:/movies # movies folder
      - ${DOWNLOADS}:/downloads # download folder
    links:
      - qbittorrent
      - jackett
    ports:
      - 7878:7878

  # For automaticly having tv shows
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGS}/sonarr:/config
      - ${DOWNLOADS}/completed/tv:/tv
      - ${DOWNLOADS}:/downloads
    ports:
      - 8989:8989
    links:
      - jackett
      - qbittorrent

  # Bazarr is a companion application to Sonarr and Radarr.
  # It can manage and download subtitles based on your requirements.
  # You define your preferences by TV show or movie and Bazarr takes care of everything for you.
  bazarr:
    image: linuxserver/bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - ${CONFIGS}/bazarr:/config
      - ${DOWNLOADS}/complete/movies:/movies
      - ${DOWNLOADS}/complete/tv:/tv
    ports:
      - 6767:6767
    links:
      - sonarr
      - radarr


  plex:
    image: ghcr.io/linuxserver/plex
    restart: always
    network_mode: host
    privileged: true
    environment:
      - VERSION=docker
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      # - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${CONFIGS}/plex:/config
      - ${CONFIGS}/plex/transcode:/transcode
      - ${DOWNLOADS}/complete/movies:/movies
      - ${DOWNLOADS}/complete/tv:/tv
      - ${DOWNLOADS}/complete/tv:/tv


  # flexget:
  #   image: wiserain/flexget
  #   restart: always
  #   environment:
  #     - PUID=${PUID} # default user id, defined in .env
  #     - PGID=${PGID} # default group id, defined in .env
  #     - TZ=${TZ} # timezone, defined in .env
  #     - FG_LOG_FILE=flexget.log
  #     - FG_WEBUI_PASSWD=${PASS}
  #     - FG_LOG_LEVEL=info
  #   ports:
  #     - 5050:5050
  #   volumes:
  #     - ./flexget:/config
  #     - /mnt/usb/torrents:/downloads
  #     - /mnt/usb/Series:/data
  #     - /mnt/usb/Movies:/data
  #     - /mnt/usb/Musica:/data
