version: "3.8"

x-common-env: &common-env
  restart: always
  environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TZ}
    # - UMASK=${UMASK}
    - WEBUI_PORT=${QBITTORRENT_WEBUI_PORT}
    - VERSION=docker

volumes:
  portainer_data:

services:
  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

  samba:
    image: dperson/samba:rpi
    restart: always
    command: '-u "${USER};{PASS}" -s "downloads;/downloads;yes;no;yes" -s "configs;/configs;yes;no;yes"'
    stdin_open: true
    tty: true
    <<: *common-env
    volumes:
      - ${DOWNLOADS}:/downloads
      - ${CONFIGS}:/configs
    ports:
      - 139:130
      - 445:445

  plex:
    image: ghcr.io/linuxserver/plex
    privileged: true
    network_mode: host
    <<: *common-env
    volumes:
      - ./traktv-plugin:${PLEXPLUGINS}/Trakttv.bundle
      - ${CONFIGS}/plex:/config
      - ${CONFIGS}/plex/db:${PLEXDB}
      - ${CONFIGS}/plex/plugins:${PLEXPLUGINS}
      - ${CONFIGS}/plex/transcode:/transcode
      - ${DOWNLOADS}:/downloads
      - ${MOVIES}:/movies
      - ${TV}:/tv
      - ${MUSIC}:/music

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent:unstable-version-4.4.0202106140855-7320-2bd5aca3aubuntu20.04.1
    <<: *common-env
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    volumes:
      - ${CONFIGS}/qbittorrent/:/config
      - ${DOWNLOADS}:/downloads

  # Feeds with torrents to radarr and sonarr
  jackett:
    image: linuxserver/jackett
    <<: *common-env
    volumes:
      - ${CONFIGS}/jackett:/config
      - ${DOWNLOADS}/blackhole:/downloads
    ports:
      - 9117:9117

  # for automaticly having movies
  radarr:
    image: linuxserver/radarr:version-3.2.2.5080
    <<: *common-env
    volumes:
      - ${CONFIGS}/radarr:/config
      - ${MOVIES}:/movies
      - ${DOWNLOADS}:/downloads
    links:
      - qbittorrent
      - jackett
    ports:
      - 7878:7878

  # For automaticly having tv shows
  medusa:
    image: ghcr.io/linuxserver/medusa
    <<: *common-env
    volumes:
      - ${CONFIGS}/medusa:/config
      - ${DOWNLOADS}:/downloads
      - ${TV}:/tv
    ports:
      - 8081:8081

  # sonarr:
  #   image: linuxserver/sonarr
  #   <<: *common-env
  #   volumes:
  #     - ${CONFIGS}/sonarr:/config
  #     # - ./configs/sonarr/:/Applications\Programs\Data\Sonar
  #     - ${DOWNLOADS}:/downloads
  #     - ${TV}:/tv
  #   ports:
  #     - 8989:8989
  #   links:
  #     - jackett
  #     - qbittorrent

  # Bazarr is a companion application to Sonarr and Radarr.
  # It can manage and download subtitles based on your requirements.
  # You define your preferences by TV show or movie and Bazarr takes care of everything for you.
  bazarr:
    image: linuxserver/bazarr
    <<: *common-env
    volumes:
      - ${CONFIGS}/bazarr:/config
      - ${MOVIES}:/movies
      - ${TV}:/tv
    ports:
      - 6767:6767
    links:
      # - sonarr
      - radarr

  # flexget:
  #   image: wiserain/flexget
  #   restart: always
  #   environment:
  #     - PUID=${PUID} # default user id, defined in .env
  #     - PGID=${PGID} # default group id, defined in .env
  #     - TZ=${TZ} # timezone, defined in .env
  #     - FG_LOG_FILE=flexget.log
  #     - FG_WEBUI_PASSWD=${PASS}
  #     - FG_LOG_LEVEL=info
  #   ports:
  #     - 5050:5050
  #   volumes:
  #     - ./flexget:/config
  #     - /mnt/usb/torrents:/downloads
  #     - /mnt/usb/Series:/data
  #     - /mnt/usb/Movies:/data
  #     - /mnt/usb/Musica:/data
