version: "3"

services:
  plex:
    image: ghcr.io/linuxserver/plex:1.23.6.4881-e2e58f321-ls66
    restart: always
    network_mode: host
    privileged: true
    environment:
      - TZ=Europe/Amsterdam
      - VERSION=docker
      - PUID=1000
      - PGID=1000
      # - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ./plex/config:/config
      - /mnt/usb/plex/transcode:/transcode # this is not strictly necessary, but I've configured Plex to use this directory for transcoding. Should make it easier to backup only the configuration and not transcoding artifacts.
      - /mnt/usb/Series:/sdcard/tv
      - /mnt/usb/Movies:/movies
      - /mnt/usb/Musica:/music
      - ${MEDIA}:/media
      - ${STORAGE}/tmp:/tmp
      - ${STORAGE}/Plex Media Server:/root/Library/Application Support/Plex Media Server

  transmission:
    image: ghcr.io/linuxserver/transmission:arm32v7-version-3.00-r2
    network_mode: host
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=${USER} #optional
      - PASS=${PASS} #optional
      - WHITELIST=192.168.*.* #optional
      # - HOST_WHITELIST=dnsnane list #optional
    volumes:
      - ./transmission/:/config
      - ${STORAGE}/torrents:/downloads
    expose:
      - 9091
    ports:
      - 9091:9091
      - 51413:51413
      - 49152:49152
      - 65535:65535
      - 51413:51413/udp

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/data:/config
      - ${MEDIA}:/tv #optional
      - ${STORAGE}/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  subs:
    build: ./subs/Dockerfile
    volumes:
      - ${MEDIA}:/media
      - ${STORAGE}/downloads:/downloads

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/config:/config
      - ${STORAGE}/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080

  flexget:
    image: wiserain/flexget
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - FG_LOG_FILE=flexget.log
      - FG_WEBUI_PASSWD=${PASS}
      - FG_LOG_LEVEL=info
    ports:
      - 5050:5050
    volumes:
      - ./flexget:/config
      - /mnt/usb/torrents:/downloads
      - /mnt/usb/Series:/data
      - /mnt/usb/Movies:/data
      - /mnt/usb/Musica:/data
