version: "3"

services:

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    restart: always
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/config:/config
      - ${DOWNLOADS}:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080

  plex:
    image: ghcr.io/linuxserver/plex:1.23.6.4881-e2e58f321-ls66
    restart: always
    network_mode: host
    privileged: true
    environment:
      - VERSION=docker
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      # - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${ROOT}/config/plex/db:/config # plex database
      - ${ROOT}/config/plex/transcode:/transcode # temp transcoded files
      - ${DOWNLOADS}:/data # media library
      - ${ROOT}/plex:/root/Library/Application Support/Plex Media Server
      - ${TV}:/tv
      - ${MOVIES}:/movies
      - ${MUSIC}:/music

  transmission:
    image: ghcr.io/linuxserver/transmission:arm32v7-version-3.00-r2
    network_mode: host
    restart: always
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=${USER} #optional
      - PASS=${PASS} #optional
      - WHITELIST=192.168.*.* #optional
      # - HOST_WHITELIST=dnsnane list #optional
    volumes:
      - ./transmission/:/config
      - ${STORAGE}/torrents:/downloads
    expose:
      - 9091
    ports:
      - 9091:9091
      - 51413:51413
      - 49152:49152
      - 65535:65535
      - 51413:51413/udp

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/sonarr:/config # config files
      - ${ROOT}/complete/tv:/tv # tv shows folder
      - ${ROOT}/downloads:/downloads # download folder
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/radarr:/config # config files
      - ${ROOT}/complete/movies:/movies # movies folder
      - ${ROOT}/downloads:/downloads # download folder

  # bazarr:
  #   container_name: bazarr
  #   image: linuxserver/bazarr
  #   restart: unless-stopped
  #   network_mode: host
  #   environment:
  #     - PUID=${PUID} # default user id, defined in .env
  #     - PGID=${PGID} # default group id, defined in .env
  #     - TZ=${TZ} # timezone, defined in .env
  #     - UMASK_SET=022 #optional
  #   volumes:
  #     - ${ROOT}/config/bazarr:/config # config files
  #     - ${ROOT}/complete/movies:/movies # movies folder
  #     - ${ROOT}/complete/tv:/tv # tv shows folder
  #   ports:
  #     - 6767:6767

  # flexget:
  #   image: wiserain/flexget
  #   restart: always
  #   environment:
  #     - PUID=${PUID} # default user id, defined in .env
  #     - PGID=${PGID} # default group id, defined in .env
  #     - TZ=${TZ} # timezone, defined in .env
  #     - FG_LOG_FILE=flexget.log
  #     - FG_WEBUI_PASSWD=${PASS}
  #     - FG_LOG_LEVEL=info
  #   ports:
  #     - 5050:5050
  #   volumes:
  #     - ./flexget:/config
  #     - /mnt/usb/torrents:/downloads
  #     - /mnt/usb/Series:/data
  #     - /mnt/usb/Movies:/data
  #     - /mnt/usb/Musica:/data
